# Generated by Django 3.2 on 2022-02-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='адрес')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='широта')),
                ('update_date', models.DateTimeField(default=None, null=True, verbose_name='дата последнего обновления')),
            ],
        ),
    ]
