# Generated by Django 3.2 on 2022-02-23 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='update_date',
            new_name='coordinates_update_date',
        ),
    ]
