# Generated by Django 3.2 on 2022-02-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_rename_update_date_address_coordinates_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='coordinates_update_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='дата последнего обновления координат'),
        ),
    ]
