# Generated by Django 3.2 on 2022-02-15 11:10

from django.db import migrations
from django.db.models import Sum, F


def fill_orders_prices(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')

    orders = Order.objects.annotate(
        new_price=(
            Sum(
                F('products__product__price') * F('products__quantity')
            )
        )
    )

    for order in orders.iterator():
        order.price = order.new_price
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_price'),
    ]

    operations = [
        migrations.RunPython(fill_orders_prices)
    ]
