# Generated by Django 3.2 on 2022-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20220215_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unperformed', 'Необработанный'), ('in work', 'В работе'), ('delivery', 'Доставляется'), ('completed', 'Выполнен'), ('rejected', 'Отменен'), ('failed', 'Завершен неудачно')], db_index=True, default='unperformed', max_length=50, verbose_name='статус'),
        ),
    ]
