# Generated by Django 3.2 on 2022-02-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220216_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_by',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно'), ('not chose', 'Не выбран')], db_index=True, default='not chose', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
