# Generated by Django 3.2 on 2022-02-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220223_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_by',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно'), ('not chosen', 'Не выбран')], db_index=True, default='not chosen', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
