# Generated by Django 3.2 on 2022-02-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20220216_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_by',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('card', 'Электронно'), ('not chose', 'Не выбран')], default='not chose', max_length=50, verbose_name='способ оплаты'),
        ),
    ]
