# Generated by Django 3.2 on 2022-02-16 11:11
from itertools import groupby
from operator import itemgetter

from django.db import migrations


def fill_orders_restaurant(apps, schema_editor):
    Order = apps.get_model(
        'foodcartapp',
        'Order'
    )
    RestaurantMenuItem = apps.get_model(
        'foodcartapp',
        'RestaurantMenuItem'
    )

    orders = Order.objects.all().prefetch_related('products')

    restaurant_with_products = [
        (order_id, [value['product_id'] for value in values])
        for order_id, values in
        groupby(
            (RestaurantMenuItem.objects.values('restaurant_id', 'product_id')
                                       .order_by('restaurant_id')
                                       .filter(availability=True)),
            key=itemgetter('restaurant_id')
        )
    ]

    for order in orders:
        order_products = order.products.values_list('product_id', flat=True)
        for restaurant_id, menu_products in restaurant_with_products:
            for order_product in order_products:
                if order_product in menu_products:
                    continue
                break
            else:
                order.restaurant_id = restaurant_id
                order.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.RunPython(fill_orders_restaurant)
    ]
